### ISSUE TITLE
cannot run on ubuntu os

### ISSUE THREAD

**Issue by zlq4863947** [MikeMcl/bignumber.js#146]
I tried to run in ubuntu os and reported the following error

```
# node dist/lib/bin/start.js
module.js:545
    throw err;
    ^

Error: Cannot find module 'BigNumber.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/tb/triangular-arbitrage/dist/lib/common/helper.js:4:24)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
```

But there is no such problem in windows os and mac os

**Comment by zlq4863947** [comment]
I solved the problem

```
import { BigNumber } from 'BigNumber.js';
```
changed to :

```
import { BigNumber } from 'bignumber.js';
```
