### ISSUE TITLE
TypeError: bignumber is not a constructor, nodejs webpack bundle

### ISSUE THREAD

**Issue by dapplion** [MikeMcl/bignumber.js#199]
In a nodejs app bignumber throws in initialization.

```
const MINUS_ONE = new bignumber(-1)
                  ^
TypeError: bignumber is not a constructor
    at Object.<anonymous> (/usr/src/app/server.bundle.js:33351:19)
    at __webpack_require__ (/usr/src/app/server.bundle.js:20:30)
    at Object.<anonymous> (/usr/src/app/server.bundle.js:24786:16)
    at __webpack_require__ (/usr/src/app/server.bundle.js:20:30)
    at Object.module.exports (/usr/src/app/server.bundle.js:85704:17)
    at __webpack_require__ (/usr/src/app/server.bundle.js:20:30)
    at Object.<anonymous> (/usr/src/app/server.bundle.js:50098:21)
    at __webpack_require__ (/usr/src/app/server.bundle.js:20:30)
    at Object.<anonymous> (/usr/src/app/server.bundle.js:48238:12)
    at __webpack_require__ (/usr/src/app/server.bundle.js:20:30)
```

bignumber version is 6.0.0, required by:
```
dnp_dappmanager@0.1.0 /path/build/src
└─┬ autobahn@18.3.2
  └─┬ cbor@4.0.0
    └── bignumber.js@6.0.0
```

bignumber is used in a webpack bundle, on node version is LTS 8.12.0, inside a docker container with image node:8.12.0-alpine in an ubuntu server host.

The code referenced by the stack is:
```
function(module, exports, __webpack_require__) {

"use strict";


const bignumber = __webpack_require__(62)
const utils = __webpack_require__(80)
const url = __webpack_require__(63)

const MINUS_ONE = new bignumber(-1)
const TEN = new bignumber(10)
const TWO = new bignumber(2)

/**
 * A CBOR tagged item, where the tag does not have semantics specified at the
 * moment, or those semantics threw an error during parsing. Typically this will
 * be an extension point you're not yet expecting.
 */
class Tagged {

```
Any help and how to fix the issue would be greatly appreciated!

**Comment by MikeMcl** [comment]
Sorry, I don't know much about webpack.

**Comment by jaimewyant** [comment]
The same issue has been raised over @ https://github.com/hildjj/node-cbor/issues/88

**Comment by MikeMcl** [comment]
Clo

**Comment by hildjj** [comment]
Please check with `cbor@4.1.5`.  I think we have a work-around, and want to make sure it works in webpack as well.
