### ISSUE TITLE
bignumber.config is not a function

### ISSUE THREAD

**Issue by aminjoharinia** [MikeMcl/bignumber.js#226]
Hi
I want to add format 
I follow docs but i can not get any result
```javascript
var BigNumber = require("big.js");
var format = {
  decimalSeparator: ".",
  groupSeparator: ",",
  groupSize: 3,
  secondaryGroupSize: 0,
  fractionGroupSeparator: " ",
  fractionGroupSize: 0
};
BigNumber.config({ FORMAT: format });

x = new BigNumber("123456789.123456789");
x.toFormat();
x.toFormat(1);

```

error 
```javascript
BigNumber.config({ FORMAT: format });
          ^

TypeError: BigNumber.config is not a function
    at Object.<anonymous> (C:\Users\Amin\Desktop\big.js:10:11)
    at Module._compile (internal/modules/cjs/loader.js:736:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
    at Function.Module._load (internal/modules/cjs/loader.js:560:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:801:12)
    at executeUserCode (internal/bootstrap/node.js:526:15)
    at startMainThreadExecution (internal/bootstrap/node.js:439:3)
```

**Comment by MikeMcl** [comment]
`var BigNumber = require("big.js");`

Wrong module!
