### ISSUE TITLE
Cannot create a Big Number

### ISSUE THREAD

**Issue by aress31** [MikeMcl/bignumber.js#291]
I am trying to create a BN object from the value `10**32`, see the following test:

```
  it("has a quadrilllion (10^15) initial total supply", async () => {
    const decimals = await this.token.decimals();
    const totalSupply = await this.token.totalSupply();
    // console.log(totalSupply);
    console.log(new BN(10 ** 32));
    // console.log((10 ** 15 * 10 ** decimals.toNumber()).toString());
    // console.log(totalSupply, expected);
    // expect(await this.token.totalSupply()).to.be.bignumber.equal(
    //   (10 ** 15 * 10 ** decimals.toNumber()).toString()
    // );
  });
```

But it seems that the library cannot handle this `Big Number`, see the following stack trace:

```
  1) Contract: Initial State
       has a quadrilllion (10^15) initial total supply:
     Error: Assertion failed
      at assert (node_modules\bn.js\lib\bn.js:6:21)
      at BN._initNumber (node_modules\bn.js\lib\bn.js:128:7)
      at BN.init [as _init] (node_modules\bn.js\lib\bn.js:82:19)
      at new BN (node_modules\bn.js\lib\bn.js:39:12)
      at Context.<anonymous> (test\ERC20Deflationary.test.js:35:17)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

I also tried to initialise the `Big Number` with a string instead but the value is totally off, see:

```
  it("has a quadrilllion (10^15) initial total supply", async () => {
    const decimals = await this.token.decimals();
    const totalSupply = await this.token.totalSupply();
    // console.log(totalSupply);
    console.log(new BN((10 ** 32).toString()));
    // console.log((10 ** 15 * 10 ** decimals.toNumber()).toString());
    // console.log(totalSupply, expected);
    // expect(await this.token.totalSupply()).to.be.bignumber.equal(
    //   (10 ** 15 * 10 ** decimals.toNumber()).toString()
    // );
  });

  Contract: Initial State
    √ the deployer is the owner (104ms)
    √ has a name (124ms)
    √ has a symbol (124ms)
    √ has 18 decimals (87ms)
BN { negative: 0, words: [ 23532 ], length: 1, red: null }
    √ has a quadrilllion (10^15) initial total supply (173ms)
    1) assigns the initial total supply to the owner
    > No events were emitted
```

Could anyone please help?

**Comment by shuckster** [comment]
```js
console.log('1', 10 ** 32)
console.log('2', new BigNumber(10 ** 32).toString())
console.log('3', new BigNumber(10).exponentiatedBy(32).toString())
// 1 1e+32
// 2 1e+32
// 3 1e+32
```
Seems fine.

Are you sure you're interpreting your test correctly?
```
  Contract: Initial State
   (...cut...)
    √ has a quadrilllion (10^15) initial total supply (173ms) <-- PASS
    1) assigns the initial total supply to the owner <-- FAIL
    > No events were emitted
```
The `it` you posted does not have the description "assigns the initial total supply to the owner"?

**Comment by aress31** [comment]
@shuckster thanks for trying to help, maybe this output will be more ufsefull:

```js
  it("has a quadrilllion (10^15) initial total supply", async () => {
    const decimals = await this.token.decimals();
    const totalSupply = await this.token.totalSupply();
    console.log(totalSupply.toString());
    console.log("1", 10 ** 32);
    console.log("2", BN(10 ** 32).toString());
    console.log("3", BN(10).exponentiatedBy(32).toString());
    // console.log(new BN(expected));
    // console.log((10 ** 15 * 10 ** decimals.toNumber()).toString());
    // console.log(totalSupply, expected);
    // expect(await this.token.totalSupply()).to.be.bignumber.equal(
    //   (10 ** 15 * 10 ** decimals.toNumber()).toString()
    // );
  });
```
```
  Contract: Initial State
    √ the deployer is the owner (76ms)
    √ has a name (110ms)
    √ has a symbol (108ms)
    √ has 18 decimals (98ms)
1000000000000000000000000000000000
1 1e+32
    1) has a quadrilllion (10^15) initial total supply
    > No events were emitted


  4 passing (1s)
  1 failing

  1) Contract: Initial State
       has a quadrilllion (10^15) initial total supply:
     TypeError: Cannot set property 'negative' of undefined
      at BN (node_modules\bn.js\lib\bn.js:26:19)
      at Context.<anonymous> (test\ERC20Deflationary.test.js:36:22)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by shuckster** [comment]
I think you're asking for help in the wrong place.

Despite being based on `bignumber.js`, the error you're getting seems more to do with the fork.

Maybe [ask bn.js](https://github.com/indutny/bn.js) for help?

**Comment by aress31** [comment]
I managed to get it work this way:
```js
    expect(await this.token.totalSupply()).to.be.bignumber.equal(
      new BigNumber(10).exponentiatedBy(33).toFixed()
    );
```

Just wondering how could I do something like that:
```js
const decimals = await this.token.decimals();
console.log(new BigNumber(10).exponentiatedBy(15 + decimals));
```

**Comment by shuckster** [comment]
Is this what you're looking for?
```js
new BigNumber(10).exponentiatedBy(15).toFormat(2)
```

**Comment by aress31** [comment]
No `decimals` is `15` basically I want to sum `15 + 18`  since `decimals` is variable and my test depends on this value.

**Comment by shuckster** [comment]
If you want the whole expression to be `BigNumber` you could do this:
```js
BigNumber(10).exponentiatedBy(BigNumber.sum(15, decimals))
```
But I don't think it's necessary?

Calculating the size of the exponent only needs integer arithmetic like you already showed:
```js
BigNumber(10).exponentiatedBy(15 + decimals)
```
That should give the same answer as the first one, right?

**Comment by aress31** [comment]
Thanks for the help @shuckster but the way I did it (15 + decimals) actually output `1518` instead of `33`.

Therefore, I think that the `BigNumber` alternative is the way to go.

**Comment by shuckster** [comment]
I just had a closer look at your error logs.

I think the problem is `this.token.decimals();` produces a string:
```js
const decimals = await this.token.decimals();
```
```js
15 + 18
// 33

15 + "18"
// "1518"

15 + decimals
// "1518", right?
```
So you could fix it like this:
```js
15 + parseInt(decimals, 10)
```
Or just make sure `this.token.decimals();` returns a number?

**Comment by aress31** [comment]
It returns a BigNumber not a string but maybe the + sign somehow force a toString() conversion, will try your version and let you know how it works. Will also try to call toNumber().

**Comment by shuckster** [comment]
Ah, if `decimals` is already a `BigNumber` then you should be able to do:
```js
decimals.plus(15)
```

**Comment by aress31** [comment]
Thanks a lot @shuckster, you helped me solved my issue. Although, I have to juggle between `BN` and `BigNumber` library which is less than optimal but `BN` does not seem to handle the very large numbers I am processing.

This is my solution:
```js
  it("has a quadrilllion (10^15) initial total supply", async () => {
    const decimals = await this.token.decimals();
    const totalSupply = await this.token.totalSupply();

    expect(await this.token.totalSupply()).to.be.bignumber.equal(
      new BigNumber(10).exponentiatedBy(decimals.add(new BN(15))).toFixed()
    );
  });
```

**Comment by shuckster** [comment]
Glad you hear you fixed it!
